apiVersion: v1
kind: Service
metadata:
  name: apache-svc
spec:
  ports:
  - port: {{ .Values.myservices.port }}
    protocol: TCP
    targetPort:  {{ .Values.myservices.port }}
  selector:
    app: apache-deployment
  type:  {{ .Values.myservices.type }}
