# setting env variable for mysql pod
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-mysql
spec:
  selector:
    app: mysql-pod
  template:
    metadata:
      name: new-pod
      labels:
        app: mysql-pod
    spec:
      containers:                                 
      - name: mysql-container 
        image: mysql
        env:                            # setting up enviromental variable
          - name: MYSQL_DATABASE
            value: mydatabase
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:                  # this keyword help to point Secret Database  
              secretKeyRef:             # this keyword help to point out value from Secret DataBase
                name: my-db-secret      
                key: MYSQL_PASSWORD
          - name: MYSQL_USER
            value: ashish
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:  
                name: my-db-secret
                key: MYSQL_PASSWORD



