apiVersion: v1
kind: ReplicationController
metadata:
  name: mynewreplicacontrroller
spec:
  selector:
    app: webserver
  template: 
    metadata:
      name: my-pod
      labels: 
        app: webserver
    spec:
      containers: 
      - name: my-weberver-container
        image: ashishizofficial/apache-php