# Role for deployment  in namespace ashish-cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-role
  namespace: ashish-cluster
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","create"]